### ISSUE TITLE
When I use creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEV_2 }} I get error

### ISSUE THREAD

**Issue by aseem-heg** [mattes/gce-cloudsql-proxy-action#11]
Does the secret variable name have to be `GOOGLE_APPLICATION_CREDENTIALS` or can it be different?
When I use a different secret name I get error - `invalid json file "/tmp/gce-cloudsql-proxy/key.json": unexpected end of JSON input`

**Comment by panjek26** [comment]
same with me

**Comment by MaximusMcCann** [comment]
Same

**Comment by ayy-em** [comment]
`exit code 124`

same json parsing trouble, I guess here, is there a solution?

**Comment by eboraks** [comment]
Same problem :(

**Comment by brettski** [comment]
This is strange. I don't see any name requirements in the YAML file, and I wonder if it's some Actions inputs limitation. If you shorten the name to something different, e.g., `GOOGLE_APP_CREDS_DEV_2`, does that work? (I don't currently have a project to test in.)

Its usage is really straightforward: https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L32 

Then read: https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L39

**Comment by kbrashem** [comment]
I know for me, I ran into the invalid JSON file error because I was pointing to my credential path, not passing the actual credentials in.

Changing:
```
     - name: Start Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          instance: ${{ env.DB_CONN_STR }}
```
to
```
      - name: Start Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GOOGLE_CREDENTIALS }}
          instance: ${{ env.DB_CONN_STR }}
```
fixed it form me.  Hope this helps someone else.
